# Generated by Django 6.0 on 2025-12-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='passport',
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
